IMPORTING REQUIRED LIBRARIES

In [2]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns
import nltk as nlp
from nltk.stem.porter import PorterStemmer
nlp.download('stopwords')
from nltk.corpus import stopwords
STOPWORDS = set(stopwords.words('english'))

from sklearn.model_selection import train_test_split
from sklearn.preprocessing import MinMaxScaler
from sklearn.feature_extraction.text import CountVectorizer
from sklearn.model_selection import cross_val_score
from sklearn.ensemble import RandomForestClassifier
from sklearn.metrics import confusion_matrix, ConfusionMatrixDisplay
from sklearn.model_selection import GridSearchCV
from sklearn.model_selection import StratifiedKFold
from sklearn.metrics import accuracy_score
! pip install wordcloud
from wordcloud import WordCloud
from sklearn.tree import DecisionTreeClassifier
! pip install xgboost
from xgboost import XGBClassifier
import pickle 
import re

[nltk_data] Downloading package stopwords to
[nltk_data]     C:\Users\akrityy\AppData\Roaming\nltk_data...
[nltk_data]   Package stopwords is already up-to-date!

Requirement already satisfied: wordcloud in c:\users\akrityy\appdata\local\programs\python\python312\lib\site-packages (1.9.4)
Requirement already satisfied: numpy>=1.6.1 in c:\users\akrityy\appdata\local\programs\python\python312\lib\site-packages (from wordcloud) (2.3.2)
Requirement already satisfied: pillow in c:\users\akrityy\appdata\local\programs\python\python312\lib\site-packages (from wordcloud) (11.3.0)
Requirement already satisfied: matplotlib in c:\users\akrityy\appdata\local\programs\python\python312\lib\site-packages (from wordcloud) (3.10.6)
Requirement already satisfied: contourpy>=1.0.1 in c:\users\akrityy\appdata\local\programs\python\python312\lib\site-packages (from matplotlib->wordcloud) (1.3.3)
Requirement already satisfied: cycler>=0.10 in c:\users\akrityy\appdata\local\programs\python\python312\lib\site-packages (from matplotlib->wordcloud) (0.12.1)
Requirement already satisfied: fonttools>=4.22.0 in c:\users\akrityy\appdata\local\programs\python\python312\lib\site-packages (from matplotlib->wordcloud) (4.59.2)
Requirement already satisfied: kiwisolver>=1.3.1 in c:\users\akrityy\appdata\local\programs\python\python312\lib\site-packages (from matplotlib->wordcloud) (1.4.9)
Requirement already satisfied: packaging>=20.0 in c:\users\akrityy\appdata\local\programs\python\python312\lib\site-packages (from matplotlib->wordcloud) (25.0)
Requirement already satisfied: pyparsing>=2.3.1 in c:\users\akrityy\appdata\local\programs\python\python312\lib\site-packages (from matplotlib->wordcloud) (3.2.3)
Requirement already satisfied: python-dateutil>=2.7 in c:\users\akrityy\appdata\local\programs\python\python312\lib\site-packages (from matplotlib->wordcloud) (2.9.0.post0)
Requirement already satisfied: six>=1.5 in c:\users\akrityy\appdata\local\programs\python\python312\lib\site-packages (from python-dateutil>=2.7->matplotlib->wordcloud) (1.17.0)

[notice] A new release of pip is available: 25.2 -> 25.3
[notice] To update, run: python.exe -m pip install --upgrade pip

Requirement already satisfied: xgboost in c:\users\akrityy\appdata\local\programs\python\python312\lib\site-packages (3.1.2)
Requirement already satisfied: numpy in c:\users\akrityy\appdata\local\programs\python\python312\lib\site-packages (from xgboost) (2.3.2)
Requirement already satisfied: scipy in c:\users\akrityy\appdata\local\programs\python\python312\lib\site-packages (from xgboost) (1.16.1)

[notice] A new release of pip is available: 25.2 -> 25.3
[notice] To update, run: python.exe -m pip install --upgrade pip

EXPLORATORY DATA ANALYSIS

In [6]:
# Load the dataset
import pandas as pd
data =  pd.read_csv(r"amazon_alexa.tsv", delimiter= '\t', quoting=3)
print(f"Dataset shape: {data.shape}")

Dataset shape: (3150, 5)

In [9]:
data.head()

,rating,date,variation,verified_reviews,feedback
0,5,31-Jul-18,Charcoal Fabric,Love my Echo!,1
1,5,31-Jul-18,Charcoal Fabric,Loved it!,1
2,4,31-Jul-18,Walnut Finish,"""Sometimes while playing a game, you can answe...",1
3,5,31-Jul-18,Charcoal Fabric,"""I have had a lot of fun with this thing. My 4...",1
4,5,31-Jul-18,Charcoal Fabric,Music,1

In [7]:
# Column names
print(f"Column names:, {data.columns.values}")

Column names:, ['rating' 'date' 'variation' 'verified_reviews' 'feedback']

In [8]:
# Check for null values
data.isnull().sum()

rating              0
date                0
variation           0
verified_reviews    1
feedback            0
dtype: int64

In [10]:
# Letting the record where 'verified_reviews' is null
data = data[data['verified_reviews'].isna() == True]

In [11]:
# drop the null record
data.dropna(inplace= True)

In [12]:
print(f"Dataset shape after dropping null values: {data.shape}")

Dataset shape after dropping null values: (0, 5)

In [13]:
# Creating a new column 'length' that will contain the length of the string in 'verified_reviews' column
data['length'] = data['verified_reviews'].apply(len)

In [16]:
data.head()

Empty DataFrame
Columns: [rating, date, variation, verified_reviews, feedback, length]
Index: []

In [ ]:
#Randomly checking for 10th record

# Original value